pull_request_rules:
  - name: backport to develop
    conditions:
      - label="backport-develop"
    actions:
      backport:
        branches:
          - develop
        assignees:
          - "{{ author }}"
          
  - name: backport to v2
    conditions:
      - label="backport-v2"
    actions:
      backport:
        branches:
          - v2
        assignees:
          - "{{ author }}"
          
  - name: backport to v1
    conditions:
      - label="backport-v1"
    actions:
      backport:
        branches:
          - v1
        assignees:
          - "{{ author }}"
