services:
  "{{STACK_NAME}}":
    image: filebrowser/filebrowser
    environment:
      - "FB_PORT=80"
      - "FB_ROOT=/srv"
      - "FB_DATABASE=/database/filebrowser.db"
      - "FB_ADDRESS=0.0.0.0" 
    volumes:
      - "{{FB_CONTENT_STORAGE}}:/srv"
      - "{{FB_DB_STORAGE}}:/database"
    expose:
      - "80/http/Filebrowser Dashboard"
docs:
  logo_url: "https://raw.githubusercontent.com/swiftwave-org/app-store/main/assets/logos/filebrowser.png"
  name: "Filebrowser"
  description: "📂 Web File Browser"
  readme_description: >
    filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files. It allows the creation of multiple users and each user can have its own directory. It can be used as a standalone app.

    ### Default Credentials

    - username - admin

    - password - admin

    ### Demo

    - url: https://demo.filebrowser.org/
    
    - credentials: demo/demo

    ### Features

    Please refer to our docs at [https://filebrowser.org/features](https://filebrowser.org/features)

    ### Links

    - Official Wesbite - [filebrowser.org](https://filebrowser.org/)

    - Github - [github.com/filebrowser/filebrowser](https://github.com/filebrowser/filebrowser)

  iframe_video_embed: ""
  variables:
    FB_CONTENT_STORAGE:
      title: "Content Storage"
      description: "The storage of content which you want to browse through filebrowser"
      default: ""
      type: volume
      options:
    FB_DB_STORAGE:
      title: "Database Storage"
      description: "The storage location for storing the Filebrowser config"
      default: ""
      type: volume
      options:
