services:
  "{{STACK_NAME}}_bench":
    image: ghcr.io/swiftwave-org/app-store/frappe-bench:{{BENCH_VERSION}}
    environment:
      - "MARIADB_DEFAULT_HOST={{MARIADB_DEFAULT_HOST}}"
    volumes:
      - "{{BENCH_STORAGE}}:/home/frappe/frappe-bench"
docs:
  logo_url: "https://raw.githubusercontent.com/swiftwave-org/app-store/main/assets/logos/frappe.png"
  name: "Frappe Bench"
  description: "Low code web framework for real world applications, in Python and Javascript"
  readme_description: >
    ### What is Frappe framework ?

    It's a Full-stack web application framework that uses Python and MariaDB on the server side and a tightly integrated client side library. Built for [ERPNext](https://erpnext.com/)

    ### Links

    - Frappe Cloud - The Official Cloud Platform for Frappe Apps  [frappecloud.com](https://frappecloud.com/)

    - Official Wesbite - [frappeframework.com](https://frappeframework.com/)

    - GitHub - [github.com/frappe/frappe](https://github.com/frappe/frappe)

    ### Read the points before installation

    - **1.** After installation, open the Application Page and go to the 'Actions' page. To access the console, click the 'Open Console' button. The console allows you to run bench commands.

    - **2.** After adding or removing a new site, run 'nginx-reload' in the 'Web Console' to restart the internal nginx server.

    - **3.** Before adding a new site, navigate to 'Application Details Page > Ingress Rules' to create a new ingress rule. During the ingress rule generation process, select the domain name (site name) and point it to 'frappe-bench' on port '80'.

  iframe_video_embed: ""
  variables:
    BENCH_VERSION:
      title: "Frappe Bench Version"
      description: "Choose one from the available one"
      default: "version-15-hotfix"
      type: options
      options:
        - title: version-15-hotfix
          value: version-15-hotfix
    MARIADB_DEFAULT_HOST:
      title: "MariaDB Default Host"
      description: "Default MariaDB host for bench"
      default: ""
      type: text
    BENCH_STORAGE:
      title: "Bench Data Storage"
      description: "The data storage for Apps & Sites"
      default: ""
      type: volume
      options:
