services:
  "{{STACK_NAME}}":
    image: gitea/gitea:1.21.11
    volumes:
      - "{{GITEA_DATA}}:/data"
    expose:
      - "3000/http/Gitea Endpoint"
docs:
  logo_url: "https://raw.githubusercontent.com/swiftwave-org/app-store/main/assets/logos/gitea.png"
  name: "Gitea"
  description: "Git with a cup of tea! Painless self-hosted all-in-one software development service, including Git hosting, code review, team collaboration, package registry and CI/CD"
  readme_description: >
    Git with a cup of tea! Painless self-hosted all-in-one software development service, including Git hosting, code review, team collaboration, package registry and CI/CD

    ### Purpose

    The goal of this project is to make the easiest, fastest, and most
    painless way of setting up a self-hosted Git service.

    As Gitea is written in Go, it works across **all** the platforms and
    architectures that are supported by Go, including Linux, macOS, and
    Windows on x86, amd64, ARM and PowerPC architectures.
    This project has been
    [forked](https://blog.gitea.com/welcome-to-gitea/) from
    [Gogs](https://gogs.io) since November of 2016, but a lot has changed.

    For online demonstrations, you can visit [try.gitea.io](https://try.gitea.io).

    For accessing free Gitea service (with a limited number of repositories), you can visit [gitea.com](https://gitea.com/user/login).

    To quickly deploy your own dedicated Gitea instance on Gitea Cloud, you can start a free trial at [cloud.gitea.com](https://cloud.gitea.com).

    ### Links

    - Official Wesbite - [gitea.com](https://gitea.com/)
    
    - Github - [github.com/go-gitea/gitea](https://github.com/go-gitea/gitea)
  iframe_video_embed: ""
  variables:
    GITEA_DATA:
      title: "Gitea Storage"
      description: "The storage location for store data of gitea"
      default: ""
      type: volume
      options:
