services:
  "{{STACK_NAME}}_nextcloud":
    image: nextcloud:29.0
    environment:
      - "POSTGRES_HOST={{POSTGRES_HOST}}"
      - "POSTGRES_DB={{POSTGRES_DB}}"
      - "POSTGRES_USER={{POSTGRES_USER}}"
      - "POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}"
      - "OVERWRITEPROTOCOL={{OVERWRITEPROTOCOL}}"
    volumes:
      - "{{NEXTCLOUD_STORAGE}}:/var/www/html"
    expose:
      - "80/http/Nextcloud Endpoint"
docs:
  logo_url: "https://raw.githubusercontent.com/swiftwave-org/app-store/main/assets/logos/nextcloud.png"
  name: "NextCloud"
  description: "A safe home for all your data. Access & share your files, calendars, contacts, mail & more from any device, on your terms"
  readme_description: >
    ### What is NextCloud?

    A safe home for all your data. Access & share your files, calendars, contacts, mail & more from any device, on your terms.

    ### Links

    - Official Wesbite - [nextcloud.com](https://nextcloud.com/)

    - GitHub - [github.com/nextcloud](https://github.com/nextcloud)

  iframe_video_embed: ""
  variables:
    OVERWRITEPROTOCOL:
      title: "NextCloud Protocol"
      description: "Select http or https based on ingress config"
      default: "https"
      type: options
      options:
        - title: "https"
          value: "https"
        - title: "http"
          value: "http"
    POSTGRES_HOST:
      title: "PostgreSQL Host"
      description: "Address of external postgres"
      default: ""
      type: text
    POSTGRES_DB:
      title: "PostgreSQL Database"
      description: "Name of the postrges database"
      default: ""
      type: text
    POSTGRES_USER:
      title: "PostgreSQL User"
      description: "Username of postgres database"
      default: ""
      type: text
    POSTGRES_PASSWORD:
      title: "PostgreSQL Password"
      description: "Password of postgres database"
      default: ""
      type: text
    NEXTCLOUD_STORAGE:
      title: "NextCloud Data Storage"
      description: "The data storage for NextCloud"
      default: ""
      type: volume
      options:
