services:
  "{{STACK_NAME}}":
    image: louislam/uptime-kuma:1
    volumes:
      - "{{UPTIME_KUMA_STORAGE}}:/app/data"
    expose:
      - "3001/http/Uptime Kuma Endpoint"
docs:
  logo_url: "https://raw.githubusercontent.com/swiftwave-org/app-store/main/assets/logos/uptime-kuma.png"
  name: "Uptime Kuma"
  description: "A fancy self-hosted monitoring tool"
  readme_description: >
    Uptime Kuma is an easy-to-use self-hosted monitoring tool.


    ### ⭐ Features

    - Monitoring uptime for HTTP(s) / TCP / HTTP(s) Keyword / HTTP(s) Json Query / Ping / DNS Record / Push / Steam Game Server / Docker Containers
    
    - Fancy, Reactive, Fast UI/UX
    
    - Notifications via Telegram, Discord, Gotify, Slack, Pushover, Email (SMTP), and [90+ notification services, click here for the full list](https://github.com/louislam/uptime-kuma/tree/master/src/components/notifications)
    
    - 20-second intervals
    
    - [Multi Languages](https://github.com/louislam/uptime-kuma/tree/master/src/lang)
    
    - Multiple status pages
    
    - Map status pages to specific domains
    
    - Ping chart
    
    - Certificate info
    
    - Proxy support
    
    - 2FA support

    ### Links

    - [Uptime Kuma Website](https://uptime.kuma.pet/)

    - [Github](https://github.com/louislam/uptime-kuma)

    ### Sponsor Uptime Kuma

    - [Github Sponsors](https://github.com/sponsors/louislam)

    - [Open Collective](https://opencollective.com/uptime-kuma)

  iframe_video_embed: ""
  variables:
    UPTIME_KUMA_STORAGE:
      title: "Storage Data"
      description: "The storage location for uptime kuma data"
      default: ""
      type: volume
      options:
